src/App.css, src/App.jsx
Preparando os arquivos do projeto, já está criada a pasta do firebase
=> Removendo e preparando arquivos para o projeto #1

package-lock.json, package.json, src/firebase/config.js
Primeiras páginas foram criadas pensando nas rotas, que será a próxima implementação
=> Criando páginas iniciais #4

src/App.jsx, src/pages/About.jsx, src/pages/Home.jsx
Rotas foram criadas. Já é possível navegar entre páginas
=> criando rotas no proejto #5

index.html, src/App.jsx, src/index.css, src/pages/Footer.jsx, src/styles/Footer.module.css
Mudanças foram feitas no footer
=> footer alteração #21

index.html, src/App.jsx, src/index.css, src/pages/Footer.jsx, src/pages/Register.jsx, src/styles/Footer.module.css
Formulário de registro criado.  Preciso alterar as rotas para que consiga validar o layout. Rotas será a próxima atualização
=> Feature/formulario de registro #20

src/App.jsx, src/pages/Login.jsx, src/pages/Navbar.jsx
adicionei o arquivo de login apenas com uma div para facilitar a edição do css. Página de login é a issue #19
=> Rotas foram criadas #24

src/index.css, src/pages/Register.jsx
Preferi colocar o css do formulário na app.css. Porque deixei todos os formulários como o mesmo estilo, caso faça alguma modificação farei em poucos arquivos;
=> css do formulario global foi criado #23

src/index.css, src/pages/Register.jsx
Lógica de registro de usuário foi feita. 
um pequeno erro foi alterado no app.css pois o botão estava sem espaçamento para o formulário 
Não teve necessidade de fazer uma issue só para isso porque foi resolvido apenas trocando de px para em
=> foi criada a logica para envio de registro #29

src/firebase/config.js, src/hooks/useAuthentication.jsx, src/index.css, src/pages/Register.jsx
Cadastro criado, já está funcionando e chegando no firebase.
=> cadastro de usuario feito e logica #28 #29

src/App.jsx, src/content/AuthContext.jsx
Começando a fazer a validação do usuário. próxima mudanças será a rota em que eles está envolvido
=> validação do login do usuario colocando hook #31

src/pages/Navbar.jsx
Botão de login e cadastrar some quando o usuário fica logado. #37
=> botão de login e cadastro ficam ocultos quando o usuário está logado #37

src/App.jsx, src/pages/CreatePost.jsx, src/pages/Dashboard.jsx, src/pages/Navbar.jsx
#39 e #40 foram feitas juntas pois uma depende da outra, já deixei criado a seguir vou começar a mexer nos dois, e fazer algumas validações, usuário não pode ter acesso a todas as páginas, preciso criar restrições na página
=> pagina de dashboard criadas junto com as rotas e lógica #40 #39

src/App.jsx, src/pages/Navbar.jsx
Usuário estava entrando no site mesmo sem ter feito login, correção de bug #42
=> usuário estava conseguindo entrar no site, mesmo sem o login. 

src/pages/Login.jsx, src/styles/Login.module.css
Login funcionando, alguma coisa já tinha sido criadas quando fiz a implementação do firebase, bastava criar a página de login
=> login está ok #47

src/pages/Navbar.jsx
=> correção do botão sair #48

src/App.jsx, src/pages/About.jsx, src/styles/About.module.css
Informações foram adicionadas na página sobre. Com botão de login.
=> informações da pagina sobre foram adicionados #45

src/hooks/useInserDocuments.jsx, src/pages/CreatePost.jsx, src/styles/CreatePost.module.css
Pacote de atualização, nessa nova branch foram feitas algumas coisa importantes no site como:
formulário para adicionar post; #52 
recebimento no firebase; #54  
validação das imagens. imagens não são obrigatórias; #54 
lógica de loading; #54 
e criação de hook para criar post. #63
=> pagina de post criada + validacao+ recebendo fomulario

src/pages/Home.jsx, src/styles/Home.module.css
página home criada, ainda faltam lógicas para concluir.  #55 
Css já está feito #65
=> pagina home criada com css #55 #65

src/hooks/useFetchDocuments.jsx, src/pages/Home.jsx, src/pages/Post.Detail.jsx, src/styles/PostDetail.module.css
Página de detail foi feita, layout está bem responsivo. #57 
pagina home está criada com css e exibindo os posts #55  #56
=> #55 #56 #57 pagina home e detail foram criadas

src/App.jsx, src/hooks/UseQuery.jsx, src/hooks/useFetchDocuments.jsx, src/pages/Home.jsx, src/pages/Search.jsx, src/styles/Search.module.css
página de busca feita com css #69
=> pagina de busca pronta #69 com css

src/index.css, src/pages/Dashboard.jsx, src/pages/Home.jsx, src/pages/Login.jsx, src/styles/Dashboard.module.css, src/styles/EditPost.module.css
=> algumas alterações no css foram feitas #77

src/pages/EditPost.jsx, src/pages/Navbar.jsx, src/pages/PostDetail.jsx, src/styles/Post.module.css, src/styles/PostDetail.module.css
=> página de rotas sem erro #84

src/index.css, src/pages/EditPost.jsx, src/pages/HomeLogado.jsx, src/styles/EditPost.css, src/styles/Home.module.css
todos os botões estão padronizados #91
=> padronização no css #91

src/pages/Error404.jsx, src/styles/Error404.css
css feito inline, coloquei em linha pois são poucos códigos. #93
=> css da página erro 404 

src/pages/Dashboard.jsx
Botão atualizado com as confirmações de deletar ou não
=> atualização botão Deletar#99

package-lock.json, package.json, src/pages/Login.jsx
correção de tela de login para a verificação de usuario
=> atualização tela de login verificação de email e senha #101
